--- 
title: "`r report_title`"
subtitle: "`r report_subtitle`"
author: "`r report_author`"
date: "`r report_date`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    css: style.css
    number_sections: false
    toc_depth: 2
    config:
      toc:
        collapse: section
    sharing:
        github: no
        facebook: no
        twitter: no
        all: no
documentclass: book
params:
  fig_path: "all_"
---

<!-- UPPERCASE variable are text to be replaced. -->
<!-- There are several global variables obtained from st_report() function. -->


```{r start, include=FALSE, echo=FALSE, eval=TRUE}
STarlight::set_verb_level(0)
library(knitr)
options(width=400)

knitr::opts_chunk$set(
  fig.path="all_",
  fig.align = "center", 
  size = "tiny", 
  comment = "",
  fig.dpi=300,
  out.width="100%"
)
library(DT)
```

# {-}

```{r panel_setup_final, include = FALSE}
xaringanExtra::use_panelset()
xaringanExtra::style_panelset(font_family = "inherit")
xaringanExtra::style_panelset_tabs(foreground = "honeydew", background = "seagreen")
```

```{r, section_gen_info_1, eval="exp_info" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("# Global ") 
``` 

```{r, section_gen_info_1, eval="exp_info" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("## Experiment {.panelset}") 
``` 


```{r, section_gen_info_2, eval="exp_info" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### General information ") 
``` 

```{r, section_gen_info_3, eval="exp_info" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("This table display metadata about the report (e.g., title, subtitle, author, and date).") 
``` 

```{r parameters, echo=FALSE, eval="exp_info" %in% section}

t1 <- rbind(c("Title: ", report_title),
            c("Subtitle: ", report_subtitle),
            c("Author", report_author),
            c("Date", report_date)
            )

knitr::kable(t1) %>% kableExtra::column_spec(1, bold = TRUE) %>%
  kableExtra::kable_styling() %>%
  kableExtra::scroll_box(width = "100%", box_css = "border: 0px;")
```

```{r, section_gen_info_4, eval="exp_info" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### Experimenters") 
``` 


```{r, section_gen_info_5, eval="exp_info" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("This table display metadata about the experimenters.") 
``` 

```{r experimenters, echo=FALSE, eval="exp_info" %in% section,}

knitr::kable(experimenters) %>% 
  kableExtra::row_spec(1, bold = TRUE) %>% 
  kableExtra::kable_styling(full_width = FALSE, position = "left") %>%
  kableExtra::kable_styling() %>%
  kableExtra::scroll_box(width = "100%", box_css = "border: 0px;")
```

```{r, section_gen_info_6, eval="exp_info" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### Sample information") 
``` 


```{r sample, echo=FALSE, eval="exp_info" %in% section}

knitr::kable(sample_info) %>% 
  kableExtra::row_spec(1, bold = TRUE) %>% 
  kableExtra::kable_styling(full_width = FALSE, position = "left") %>%
  kableExtra::kable_styling() %>%
  kableExtra::scroll_box(width = "100%", box_css = "border: 0px;")
```

```{r, section_gen_info_5, eval="exp_info" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### Workflow parameters.") 
``` 
  
```{r, section_gen_info_6, eval="exp_info" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("This table display informations about the worflow parameters.") 
``` 

```{r parameters, echo=FALSE, eval="exp_info" %in% section}

t1 <- rbind(c("Nb of modules: ", hc_tree_params[['class_nb']]),
            c("Image height: ", image_height)
            )

knitr::kable(t1) %>% kableExtra::column_spec(1, bold = TRUE) %>%
  kableExtra::kable_styling() %>%
  kableExtra::scroll_box(width = "100%", box_css = "border: 0px;")
```

```{r, section_exp_count_1, eval="exp_count" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("## Counts {.panelset}") 
``` 

```{r, section_exp_count_2, eval="exp_count" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("This section provide an overview of total counts across samples.") 
```

```{r, section_exp_count_3, eval="exp_count" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### Total counts (linear)") 
``` 

```{r distributions_raw, echo=FALSE, eval="exp_count" %in% section, fig.height=4.5}
STarlight::cmp_counts_st(st_grid_list, features=c("count_sum"))
```

```{r, section_exp_count_4, eval="exp_count" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### Total counts (log10)") 
``` 

```{r distributions_log, echo=FALSE, eval="exp_count" %in% section, fig.height=4.5}
STarlight::cmp_counts_st(st_grid_list, features=c("count_sum"), 
                         transform = "log10")
```


```{r, section_exp_count_dist_1, eval="exp_count_dist" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("## Count distributions {.panelset}") 
``` 

```{r, section_exp_count_dist_2, eval="exp_count_dist" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("This section provides information about feature count distribution across samples.") 
``` 

```{r, section_exp_count_dist_3, eval="exp_count_dist" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### Count distribution (linear)") 
``` 

```{r distributions_raw, echo=FALSE, eval="exp_count_dist" %in% section, fig.height=4.5}
STarlight::dist_st(st_grid_list) + Seurat::NoLegend()
```

```{r, section_exp_count_dist_3, eval="exp_count_dist" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### Count distribution (log10)") 
``` 


```{r distributions_log, echo=FALSE, eval="exp_count_dist" %in% section, fig.height=4.5}
STarlight::dist_st(st_grid_list, transform="log10") + Seurat::NoLegend()
```

```{r, section_exp_area_1, eval="exp_area" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("## Region dimensions {.panelset}") 
``` 

```{r, section_exp_area_2, eval="exp_area" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("This section present some informations regarding the dimension of the region that were analyzed. The units are according the provided x/y coordinates. Area is computed as `(x_max - x_min)*(y_max - y_min)`") 
``` 

```{r, section_exp_area_3, eval="exp_area" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### Area") 
``` 

```{r section_exp_area_4, eval="exp_area" %in% section, echo=FALSE, results = "asis"} 
STarlight::cmp_dimensions(st_grid_list)
```

```{r, section_exp_area_5, eval="exp_area" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### X dimension") 
``` 

```{r section_exp_area_6, eval="exp_area" %in% section, echo=FALSE, results = "asis"} 
STarlight::cmp_dimensions(st_grid_list, type="x_size")
```

```{r, section_exp_area_7, eval="exp_area" %in% section, echo=FALSE, results = "asis"} 
knitr::asis_output("### Y dimension") 
``` 

```{r section_exp_area_8, eval="exp_area" %in% section, echo=FALSE, results = "asis"} 
STarlight::cmp_dimensions(st_grid_list, type="y_size")
```

