--- 
title: "REPORT_TITLE"
subtitle: "REPORT_SUBTITLE"
author: "REPORT_AUT"
date: "REPORT_DATE"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    css: style.css
    number_sections: false
    config:
      toc:
        collapse: section
    sharing:
        github: no
        facebook: no
        twitter: no
        all: no
documentclass: book
params:
  fig_path: "all_"
---


<!-- UPPERCASE variable are text to be replaced. -->
<!-- There are several global variables obtained from st_report() function. -->


```{r start, include=FALSE, echo=FALSE, eval=TRUE}
STarlight::set_verb_level(0)
library(knitr)
options(width=400)

knitr::opts_chunk$set(
  fig.path="FIG_PATH",
  fig.align = "center", 
  size = "tiny", 
  comment = "",
  fig.dpi=300,
  out.width="100%"
)
library(DT)
```

# Présentation

```{r panel_setup_final, include = FALSE}
xaringanExtra::use_panelset()
xaringanExtra::style_panelset(font_family = "inherit")
xaringanExtra::style_panelset_tabs(foreground = "honeydew", background = "seagreen")
```

# General information {.panelset}

## Experimenters

```{r experimenters, echo=FALSE, eval=TRUE}

knitr::kable(experimenters) %>% 
  kableExtra::row_spec(1, bold = TRUE) %>% 
  kableExtra::kable_styling(full_width = FALSE, position = "left") %>%
  kableExtra::kable_styling() %>%
  kableExtra::scroll_box(width = "100%", box_css = "border: 0px;")
```

## Sample information  


```{r sample, echo=FALSE, eval=TRUE}

knitr::kable(sample_info) %>% 
  kableExtra::row_spec(1, bold = TRUE) %>% 
  kableExtra::kable_styling(full_width = FALSE, position = "left") %>%
  kableExtra::kable_styling() %>%
  kableExtra::scroll_box(width = "100%", box_css = "border: 0px;")
```

## Workflow parameters  


```{r parameters, echo=FALSE, eval=TRUE}

t1 <- rbind(c("Date: ", date),
            c("Nb of modules: ", hc_tree_params[['class_nb']]),
            c("Image height: ", image_height)
            )

knitr::kable(t1) %>% kableExtra::column_spec(1, bold = TRUE) %>%
  kableExtra::kable_styling() %>%
  kableExtra::scroll_box(width = "100%", box_css = "border: 0px;")
```


# Count distributions {.panelset}

## Raw linear

```{r distributions_raw, echo=FALSE, eval=TRUE}

STarlight::dist_st(st_grid_list) + Seurat::NoLegend()
```

## Raw log (log10)

```{r distributions_log, echo=FALSE, eval=TRUE}

STarlight::dist_st(st_grid_list, transform="log10") + Seurat::NoLegend()
```

## Normalized (log10)

```{r distributions_norm, echo=FALSE, eval=TRUE}

STarlight::dist_st(st_grid_list, 
                   transform="log10", 
                   normalized = TRUE) + Seurat::NoLegend()
```

# Comparisons

## todo

ezretr

